Add handling of misconfigured $GOPATH/bin
`g` now throws when `$GOPATH/bin` is not listed in the `$PATH`, since
it is crutial for many commands that depend on the go binaries being
called with `command` and `g` itself for self-upgrade.

Also handle installation failing when trying to link the go binaries
if the `$GOPATH/bin/` dir doesn't exists, which is usually handled by
g-install, but nontheless found missing while doing some testing
without g-install.

diff --git a/bin/g b/bin/g
--- a/bin/g
+++ b/bin/g
@@ -721,6 +721,22 @@ if [ -z "${GOPATH:-}" ] || [ -z "${GOROOT:-}" ]; then
   exit 1
 fi
 
+BIN_DIR="$GOPATH/bin"
+
+if [ "${PATH##*$BIN_DIR*}" == "$PATH" ]; then
+  error "\$GOPATH/bin not found in \$PATH and it is required."
+  display_help
+  exit 1
+fi
+
+#
+# Create bin dir inside GOPATH if it doesn't exists yet
+#
+
+if [ ! -d "$BIN_DIR" ]; then
+  mkdir -p "$BIN_DIR"
+fi
+
 #
 # create versions dir if it doesn't exist yet.
 #
